project_id = "aczkjkkiiqrvljlrkccw"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.delete-account]
    verify_jwt = false
  [functions.retry-notifications]
    verify_jwt = false
  [functions.send-order-email]
    verify_jwt = false
  [functions.send-promotional-notifications]
    verify_jwt = false
  [functions.send-push-notification]
    verify_jwt = false
  [functions.support-chat]
    verify_jwt = false
  [functions.unsubscribe]
    verify_jwt = false
