import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { Send, Megaphone, Lightbulb, Users, UserMinus, Loader2, Zap, Calendar, UserX, Star } from "lucide-react";

const NOTIFICATION_TYPES = [
  { value: "custom", label: "Custom Message", icon: Megaphone, description: "Write your own notification" },
  { value: "flash_sale", label: "Flash Sale", icon: Zap, description: "Time-limited deals & discounts" },
  { value: "seasonal", label: "Seasonal Promo", icon: Calendar, description: "Holiday & seasonal messages" },
  { value: "win_back", label: "Win-back", icon: UserX, description: "Re-engage inactive users" },
  { value: "personalized", label: "Personalized", icon: Star, description: "Based on user order history" },
  { value: "daily_tip", label: "Daily Tip Mix", icon: Lightbulb, description: "Random mix of all types" },
];

const PRESETS = [
  { title: "🔥 Limited Time Offer!", message: "Get 20% off your next delivery! Use code SAVE20 at checkout. Valid for 48 hours only!", target: "all" },
  { title: "🍔 New Restaurant Alert!", message: "Check out our newest restaurant partner on the marketplace! Order now and earn double loyalty points.", target: "all" },
  { title: "👋 We Miss You!", message: "It's been a while! Come back and enjoy a special discount on your next order. We've got exciting new features waiting for you!", target: "inactive" },
  { title: "🎁 Refer & Earn!", message: "Share your referral code with friends and earn credits when they complete their first order! Check your profile for your code.", target: "all" },
];

const AdminPromotions = () => {
  const [title, setTitle] = useState("");
  const [message, setMessage] = useState("");
  const [target, setTarget] = useState("all");
  const [notificationType, setNotificationType] = useState("custom");
  const [sending, setSending] = useState(false);

  const isAutoGenerated = notificationType !== "custom";

  const sendPromotion = async () => {
    if (!isAutoGenerated && (!title.trim() || !message.trim())) {
      return toast.error("Title and message are required for custom notifications");
    }
    setSending(true);
    try {
      const body: Record<string, string> = { type: notificationType, target };
      if (!isAutoGenerated) {
        // For non-custom, the edge function generates the message
      } else {
        body.type = "custom";
        body.title = title.trim();
        body.message = message.trim();
      }
      if (notificationType === "custom") {
        body.title = title.trim();
        body.message = message.trim();
      }

      const { data, error } = await supabase.functions.invoke("send-promotional-notifications", { body });
      if (error) throw error;
      toast.success(`Sent to ${data.sent} users! 🚀`);
      if (notificationType === "custom") {
        setTitle("");
        setMessage("");
      }
    } catch (err: any) {
      toast.error(err.message || "Failed to send");
    } finally {
      setSending(false);
    }
  };

  const applyPreset = (preset: typeof PRESETS[0]) => {
    setNotificationType("custom");
    setTitle(preset.title);
    setMessage(preset.message);
    setTarget(preset.target);
  };

  const selectedType = NOTIFICATION_TYPES.find(t => t.value === notificationType);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="font-display text-xl font-bold flex items-center gap-2">
          <Megaphone className="h-5 w-5 text-primary" /> Promotional Notifications
        </h2>
      </div>

      {/* Notification type selector */}
      <div>
        <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">Notification Type</p>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
          {NOTIFICATION_TYPES.map((type) => {
            const Icon = type.icon;
            const isActive = notificationType === type.value;
            return (
              <button
                key={type.value}
                onClick={() => setNotificationType(type.value)}
                className={`text-left rounded-xl p-3 transition-all text-xs border ${
                  isActive
                    ? "border-primary bg-primary/10 shadow-md"
                    : "border-border/50 bg-card hover:border-primary/30 hover:shadow-sm"
                }`}
              >
                <div className="flex items-center gap-1.5 mb-1">
                  <Icon className={`h-3.5 w-3.5 ${isActive ? "text-primary" : "text-muted-foreground"}`} />
                  <span className="font-semibold text-foreground">{type.label}</span>
                </div>
                <p className="text-muted-foreground line-clamp-1">{type.description}</p>
              </button>
            );
          })}
        </div>
      </div>

      {/* Quick presets - only for custom */}
      {notificationType === "custom" && (
        <div>
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">Quick Templates</p>
          <div className="grid grid-cols-2 gap-2">
            {PRESETS.map((p, i) => (
              <button
                key={i}
                onClick={() => applyPreset(p)}
                className="text-left bg-card border border-border/50 rounded-xl p-3 hover:border-primary/30 hover:shadow-md transition-all text-xs"
              >
                <p className="font-semibold text-foreground truncate">{p.title}</p>
                <p className="text-muted-foreground mt-0.5 line-clamp-2">{p.message}</p>
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Form */}
      <div className="bg-card border border-border/50 rounded-2xl p-5 space-y-4">
        {isAutoGenerated && (
          <div className="bg-primary/5 border border-primary/20 rounded-xl p-3 text-xs text-muted-foreground flex items-start gap-2">
            {selectedType && <selectedType.icon className="h-4 w-4 text-primary mt-0.5 shrink-0" />}
            <span>
              <strong className="text-foreground">{selectedType?.label}</strong> — Messages will be auto-generated by the system.
              {notificationType === "personalized" && " Each user gets a unique message based on their order history."}
              {notificationType === "win_back" && " Targets users inactive for 7+ days with re-engagement offers."}
              {notificationType === "flash_sale" && " Sends a randomized flash sale promotion."}
              {notificationType === "seasonal" && " Sends a seasonal/holiday themed promotion."}
              {notificationType === "daily_tip" && " Randomly picks from seasonal, flash sale, and general tips."}
            </span>
          </div>
        )}

        {notificationType === "custom" && (
          <>
            <div className="space-y-2">
              <Label>Notification Title</Label>
              <Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g. 🔥 Flash Sale Today!" />
            </div>
            <div className="space-y-2">
              <Label>Message</Label>
              <Textarea value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Write your promotional message..." rows={3} />
            </div>
          </>
        )}

        <div className="space-y-2">
          <Label>Target Audience</Label>
          <Select value={target} onValueChange={setTarget}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">
                <span className="flex items-center gap-2"><Users className="h-3.5 w-3.5" /> All Customers</span>
              </SelectItem>
              <SelectItem value="inactive">
                <span className="flex items-center gap-2"><UserMinus className="h-3.5 w-3.5" /> Inactive Users (7+ days)</span>
              </SelectItem>
            </SelectContent>
          </Select>
        </div>

        <Button
          className="w-full gap-2"
          onClick={sendPromotion}
          disabled={sending || (notificationType === "custom" && (!title.trim() || !message.trim()))}
        >
          {sending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
          Send {selectedType?.label} to {target === "all" ? "All Customers" : "Inactive Users"}
        </Button>
      </div>
    </div>
  );
};

export default AdminPromotions;
